package cognition

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/Thynaptic/P-LMv1/pkg/memory"
	"github.com/Thynaptic/P-LMv1/pkg/state"
)

const (
	defaultReflectionLogPath = ".memory/reflection_log.json"
	driftThreshold           = 0.40
	highDriftThreshold       = 0.25
)

// NodeOutputEvent is emitted by ThoughtGraph nodes for concurrent supervision.
type NodeOutputEvent struct {
	NodeID    string    `json:"node_id"`
	Step      int       `json:"step"`
	Input     string    `json:"input"`
	Output    string    `json:"output"`
	NextNode  string    `json:"next_node"`
	Timestamp time.Time `json:"timestamp"`
}

// SteerSignal indicates branch pruning + recovery routing.
type SteerSignal struct {
	NodeID    string    `json:"node_id"`
	Step      int       `json:"step"`
	Goal      string    `json:"goal"`
	Relevance float64   `json:"relevance"`
	Reason    string    `json:"reason"`
	Timestamp time.Time `json:"timestamp"`
}

type reflectionLogEntry struct {
	Timestamp     time.Time `json:"timestamp"`
	NodeID        string    `json:"node_id"`
	Step          int       `json:"step"`
	Goal          string    `json:"goal"`
	Relevance     float64   `json:"relevance"`
	Reason        string    `json:"reason"`
	OutputPreview string    `json:"output_preview"`
}

// ReflectionLayer monitors node outputs concurrently and emits steer signals on drift.
type ReflectionLayer struct {
	sm      *state.Manager
	mm      *memory.MemoryManager
	goal    string
	logPath string
	pred    *PredictiveForecaster

	inputCh chan NodeOutputEvent
	steerCh chan SteerSignal
	stopCh  chan struct{}
	wg      sync.WaitGroup
	mu      sync.RWMutex
}

// NewReflectionLayer creates a reflection layer bound to current session state.
func NewReflectionLayer(sm *state.Manager, goal string) *ReflectionLayer {
	return &ReflectionLayer{
		sm:      sm,
		goal:    strings.TrimSpace(goal),
		logPath: defaultReflectionLogPath,
		inputCh: make(chan NodeOutputEvent, 32),
		steerCh: make(chan SteerSignal, 8),
		stopCh:  make(chan struct{}),
	}
}

// SetLogPath overrides the reflection log path.
func (r *ReflectionLayer) SetLogPath(path string) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if strings.TrimSpace(path) != "" {
		r.logPath = strings.TrimSpace(path)
	}
}

// AttachPredictive enables proactive forecasting during reflection.
func (r *ReflectionLayer) AttachPredictive(pred *PredictiveForecaster) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.pred = pred
}

// AttachMemory enables symbolic verification against live shell evidence in memory.
func (r *ReflectionLayer) AttachMemory(mm *memory.MemoryManager) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.mm = mm
}

// PredictiveNotices returns latest proactive interventions generated by reflection.
func (r *ReflectionLayer) PredictiveNotices() []string {
	r.mu.RLock()
	p := r.pred
	r.mu.RUnlock()
	if p == nil {
		return nil
	}
	return p.Notices()
}

// BindGoal updates monitoring goal at runtime.
func (r *ReflectionLayer) BindGoal(goal string) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.goal = strings.TrimSpace(goal)
}

// Start starts concurrent supervision worker.
func (r *ReflectionLayer) Start() {
	if r == nil {
		return
	}
	r.wg.Add(1)
	go r.loop()
}

// Stop stops worker and drains.
func (r *ReflectionLayer) Stop() {
	if r == nil {
		return
	}
	close(r.stopCh)
	r.wg.Wait()
}

// Publish sends node output for concurrent reflection.
func (r *ReflectionLayer) Publish(ev NodeOutputEvent) {
	if r == nil {
		return
	}
	select {
	case r.inputCh <- ev:
	default:
		// Drop if overloaded; graph must keep moving.
	}
}

// WaitForSteer waits briefly for a steer signal.
func (r *ReflectionLayer) WaitForSteer(timeout time.Duration) (SteerSignal, bool) {
	if r == nil {
		return SteerSignal{}, false
	}
	if timeout <= 0 {
		select {
		case sig := <-r.steerCh:
			return sig, true
		default:
			return SteerSignal{}, false
		}
	}
	timer := time.NewTimer(timeout)
	defer timer.Stop()
	select {
	case sig := <-r.steerCh:
		return sig, true
	case <-timer.C:
		return SteerSignal{}, false
	}
}

func (r *ReflectionLayer) loop() {
	defer r.wg.Done()
	for {
		select {
		case <-r.stopCh:
			return
		case ev := <-r.inputCh:
			r.evaluateEvent(ev)
		}
	}
}

func (r *ReflectionLayer) evaluateEvent(ev NodeOutputEvent) {
	r.mu.RLock()
	pred := r.pred
	mm := r.mm
	r.mu.RUnlock()
	if pred != nil {
		pred.EvaluateAsync(ev.NodeID)
	}
	if strings.TrimSpace(ev.Output) != "" {
		session := state.SessionState{}
		if r.sm != nil {
			session = r.sm.GetSnapshot()
		}
		shellFacts := CollectLiveShellFacts(mm, ev.Output, 10)
		symbolic := CheckSymbolicAssertions(ev.Output, session, shellFacts)
		if symbolic.Veto {
			reason := "symbolic veto: " + symbolic.Violations[0]
			sig := SteerSignal{
				NodeID:    ev.NodeID,
				Step:      ev.Step,
				Goal:      r.currentGoal(),
				Relevance: 0,
				Reason:    reason,
				Timestamp: time.Now().UTC(),
			}
			if r.sm != nil {
				r.sm.UpdateDelta(map[string]float64{
					"AnalyticalMode": 0.18,
					"Frustration":    0.10,
				})
				_ = r.sm.Save()
			}
			r.appendLog(reflectionLogEntry{
				Timestamp:     sig.Timestamp,
				NodeID:        ev.NodeID,
				Step:          ev.Step,
				Goal:          sig.Goal,
				Relevance:     0,
				Reason:        reason,
				OutputPreview: truncate(strings.TrimSpace(ev.Output), 320),
			})
			select {
			case r.steerCh <- sig:
			default:
				select {
				case <-r.steerCh:
				default:
				}
				select {
				case r.steerCh <- sig:
				default:
				}
			}
			return
		}
	}

	goal := r.currentGoal()
	if goal == "" {
		return
	}
	relevance := relevanceScore(goal, ev.Output)
	if relevance >= driftThreshold {
		return
	}

	reason := "goal drift detected"
	if relevance < highDriftThreshold {
		reason = "severe goal drift detected"
	}
	sig := SteerSignal{
		NodeID:    ev.NodeID,
		Step:      ev.Step,
		Goal:      goal,
		Relevance: relevance,
		Reason:    reason,
		Timestamp: time.Now().UTC(),
	}

	if r.sm != nil {
		delta := map[string]float64{
			"AnalyticalMode": 0.08,
			"Frustration":    0.05,
		}
		if relevance < highDriftThreshold {
			delta["AnalyticalMode"] = 0.14
			delta["Frustration"] = 0.10
		}
		r.sm.UpdateDelta(delta)
		_ = r.sm.Save()
	}
	r.appendLog(reflectionLogEntry{
		Timestamp:     sig.Timestamp,
		NodeID:        ev.NodeID,
		Step:          ev.Step,
		Goal:          goal,
		Relevance:     relevance,
		Reason:        reason,
		OutputPreview: truncate(strings.TrimSpace(ev.Output), 320),
	})

	select {
	case r.steerCh <- sig:
	default:
		// If steering channel full, keep newest intent by replacing one.
		select {
		case <-r.steerCh:
		default:
		}
		select {
		case r.steerCh <- sig:
		default:
		}
	}
}

func (r *ReflectionLayer) currentGoal() string {
	r.mu.RLock()
	goal := r.goal
	r.mu.RUnlock()
	if strings.TrimSpace(goal) != "" {
		return strings.TrimSpace(goal)
	}
	if r.sm != nil {
		return strings.TrimSpace(r.sm.GetSnapshot().PrimaryGoal)
	}
	return ""
}

func (r *ReflectionLayer) appendLog(entry reflectionLogEntry) {
	r.mu.Lock()
	defer r.mu.Unlock()

	path := r.logPath
	if path == "" {
		path = defaultReflectionLogPath
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return
	}

	var existing []reflectionLogEntry
	if b, err := os.ReadFile(path); err == nil && len(b) > 0 {
		_ = json.Unmarshal(b, &existing)
	}
	existing = append(existing, entry)
	if len(existing) > 2000 {
		existing = existing[len(existing)-2000:]
	}
	data, err := json.MarshalIndent(existing, "", "  ")
	if err != nil {
		return
	}
	_ = os.WriteFile(path, data, 0o644)
}

func relevanceScore(goal, output string) float64 {
	g := tokenizeReflection(goal)
	o := tokenizeReflection(output)
	if len(g) == 0 || len(o) == 0 {
		return 0.0
	}

	goalSet := make(map[string]bool, len(g))
	for _, t := range g {
		goalSet[t] = true
	}
	shared := 0
	for _, t := range o {
		if goalSet[t] {
			shared++
		}
	}
	ratio := float64(shared) / float64(len(goalSet))
	if strings.Contains(strings.ToLower(output), strings.ToLower(goal)) {
		ratio += 0.25
	}
	if ratio > 1 {
		ratio = 1
	}
	return ratio
}

func tokenizeReflection(s string) []string {
	s = strings.ToLower(strings.TrimSpace(s))
	repl := strings.NewReplacer(",", " ", ".", " ", ";", " ", ":", " ", "(", " ", ")", " ", "[", " ", "]", " ", "{", " ", "}", " ", "/", " ", "\\", " ")
	s = repl.Replace(s)
	stop := map[string]bool{
		"the": true, "and": true, "for": true, "with": true, "that": true, "this": true,
		"from": true, "your": true, "into": true, "have": true, "been": true, "about": true,
	}
	seen := make(map[string]bool)
	var out []string
	for _, t := range strings.Fields(s) {
		if len(t) < 3 || stop[t] || seen[t] {
			continue
		}
		seen[t] = true
		out = append(out, t)
	}
	return out
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	if n < 4 {
		return s[:n]
	}
	return s[:n-3] + "..."
}
